<?php
// $Id: taxonomy_service.module,v 1.4.2.9.2.4 2010/02/28 01:15:31 heyrocker Exp $
/**
 * @file
 *  Link general taxonomy functionalities to services module.
 */

function _taxonomy_resource_access($op = 'view', $args = array()) {
  if (user_access('administer taxonomy')) {
    return TRUE;
  }

  // TODO - check perms of user to return ability to interact with terms / vocabulary
}

function taxonomy_resource_services_resources() {
  return array(
    'taxonomy_term' => array(
      'file' => array('type' => 'inc', 'module' => 'taxonomy_resource'),
      'retrieve' => array(
        'callback' => '_taxonomy_term_resource_retrieve',
        'args' => array(
          array(
            'name' => 'tid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The tid of the taxonomy term to get',
          ),
        ),
        'access callback' => '_taxonomy_resource_access',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
      ),
      'create' => array(
        'callback' => '_taxonomy_term_resource_create',
        'args' => array(
          array(
            'name' => 'term',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The taxonomy term object to create',
            'type' => 'struct',
          ),
        ),
        'access callback' => '_taxonomy_resource_access',
        'access arguments' => array('create'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'callback' => '_taxonomy_term_resource_update',
        'args' => array(
          array(
            'name' => 'term',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The taxonomy term data to update',
            'type' => 'struct',
          ),
        ),
        'access callback' => '_taxonomy_resource_access',
        'access arguments' => array('update'),
        'access arguments append' => TRUE,
      ),
      'delete' => array(
        'callback' => '_taxonomy_term_resource_delete',
        'args' => array(
          array(
            'name' => 'tid',
            'optional' => FALSE,
            'source' => array('path' => 0),
          ),
        ),
        'access callback' => '_taxonomy_resource_access',
        'access arguments' => array('delete'),
        'access arguments append' => TRUE,
      ),
      // TODO: term specific actions need to be implemented (see: taxonomy_service_get_tree / taxonomy_service_select_nodes)
    ),
  'taxonomy_vocabulary' => array(
    'file' => array('type' => 'inc', 'module' => 'taxonomy_resource'),
    'retrieve' => array(
      'callback' => '_taxonomy_vocabulary_resource_retrieve',
      'args' => array(
        array(
          'name' => 'vid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'int',
          'description' => 'The vid of the taxonomy vocabulary to get',
        ),
      ),
      'access callback' => '_taxonomy_resource_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
    'create' => array(
      'callback' => '_taxonomy_vocabulary_resource_create',
      'args' => array(
        array(
          'name' => 'vocabulary',
          'optional' => FALSE,
          'source' => 'data',
          'description' => 'The taxonomy vocabulary object to create',
          'type' => 'struct',
        ),
      ),
      'access callback' => '_taxonomy_resource_access',
      'access arguments' => array('create'),
      'access arguments append' => TRUE,
    ),
    'update' => array(
      'callback' => '_taxonomy_vocabulary_resource_update',
      'args' => array(
        array(
          'name' => 'vocabulary',
          'optional' => FALSE,
          'source' => 'data',
          'description' => 'The taxonomy vocabulary data to update',
          'type' => 'struct',
        ),
      ),
      'access callback' => '_taxonomy_resource_access',
      'access arguments' => array('update'),
      'access arguments append' => TRUE,
    ),
    'delete' => array(
      'callback' => '_taxonomy_vocabulary_resource_delete',
      'args' => array(
        array(
          'name' => 'vid',
          'optional' => FALSE,
          'source' => array('path' => 0),
        ),
      ),
      'access callback' => '_taxonomy_resource_access',
      'access arguments' => array('delete'),
      'access arguments append' => TRUE,
    ),
  ),
  );
}
