<?php
// $Id$

/**
 * Implementation of hook_services_authentication().
 */
function services_oauth_authentication_info() {
  return array(
    '#file' => 'services_oauth.inc',
    '#title' => t('OAuth authentication'),
    '#description' => t('An open protocol to allow secure API authorization'),
    '#context_aware' => TRUE,
    'security_settings' => '_services_oauth_security_settings',
    'alter_methods' => '_services_oauth_alter_methods',
    'authenticate_call' => '_services_oauth_authenticate_call',
  );
}

function services_oauth_services_resource_operation_settings_alter(&$settings, $context, $resource, $class, $name=NULL) {
  require_once('services_oauth.admin.inc');
  if ($context['authentication'] == 'services_oauth') {
    $oauth_context = $context['authentication_settings']['oauth_context'];
    if ($rop = get_resource_operation_info($resource, $class, $name)) {
      $auth_levels = array();
      foreach (oauth_common_authorization_levels($oauth_context) as $name => $level) {
        $auth_levels[$name] = t($level->title);
      }
      _services_oauth_admin_authentication_options($settings, $rop, $auth_levels);
    }
  }
}